/**
 * docs/designs/components/index.html is the design-side record: every component
 * painted by its own shipped CSS on one page, generated by scripts/build-design.mjs.
 * It is pinned to the generator the way docs/properties.md and the token file are, it
 * must open from disk like a demo, and its optional Claude Design projection - the
 * canvas directory beside it - is pinned whenever it exists.
 */
import { describe, expect, it } from 'vitest';
import { existsSync, readFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';

const ROOT = resolve(import.meta.dirname, '../..');
const SHEET = resolve(ROOT, 'docs/designs/components/index.html');
const CANVAS = resolve(ROOT, 'docs/designs/components/canvas/canvas.json');

/** The same pattern scripts/check.sh runs over skills/, with the same three exemptions. */
const EXTERNAL = /<link[^>]+href=|\ssrc(?:set)?=|@import|url\(/g;
const EXEMPT = /^(?:src="data:|url\(data:|url\(#)/;

const html = existsSync(SHEET) ? readFileSync(SHEET, 'utf8') : '';

describe('docs/designs/components/index.html is the generator output', () => {
  it('exists', () => {
    expect(existsSync(SHEET), 'run: node scripts/build-design.mjs').toBe(true);
  });

  it('equals render() from scripts/build-design.mjs byte for byte', async () => {
    const { render } = await import('../../scripts/build-design.mjs');
    expect(html).toBe(render());
  });

  it('loads nothing external, so it opens from disk exactly like a demo', () => {
    const hits = [...html.matchAll(EXTERNAL)].map((m) => m[0].trimStart()).filter((hit) => !EXEMPT.test(hit));
    expect(hits).toEqual([]);
  });

  it('renders every component root class', () => {
    for (const slug of ['alert', 'box', 'button', 'dialog', 'popover', 'tabs']) {
      expect(html, `no auk-${slug} on the sheet`).toContain(`class="auk-${slug}`);
    }
  });
});

describe('the canvas projection, when present, is the generator output too', () => {
  it('canvas.json and every artboard it lists equal renderCanvas()', async () => {
    if (!existsSync(CANVAS)) return;
    const { renderCanvas } = await import('../../scripts/build-design.mjs');
    const files = renderCanvas();
    expect(readFileSync(CANVAS, 'utf8')).toBe(files['canvas.json']);
    const listed = JSON.parse(files['canvas.json']).artboards.map((a: { file: string }) => a.file);
    expect(listed.length).toBeGreaterThan(0);
    for (const file of listed) {
      const path = resolve(dirname(CANVAS), file);
      expect(existsSync(path), `${file} listed in canvas.json is missing`).toBe(true);
      expect(readFileSync(path, 'utf8'), `${file} differs from renderCanvas()`).toBe(files[file]);
    }
  });
});

describe('validateRoles guards the --roles preview', () => {
  it('names a misspelled role', async () => {
    const { validateRoles } = await import('../../scripts/build-design.mjs');
    expect(() => validateRoles(':root { --auk-role-primry: #000; --auk-role-text: #111; }')).toThrow(/--auk-role-primry/);
    expect(() => validateRoles(':root { --auk-role-primary: #000; }')).not.toThrow();
  });
});
