/**
 * docs/designs/components/index.html is the design-side record: every component's
 * Structure block painted by its shipped CSS on one page, generated by
 * scripts/build-design.mjs. It is pinned the way docs/properties.md and the token
 * files are, so it cannot drift from the references, and it must open from disk under
 * the same no-external-resource rule as the demos. The canvas projection, when it
 * exists, is pinned the same way.
 */
import { describe, expect, it } from 'vitest';
import { existsSync, readFileSync, readdirSync } from 'node:fs';
import { spawnSync } from 'node:child_process';
import { resolve } from 'node:path';
import { skillKind } from '../../scripts/skill-kind.mjs';

const ROOT = resolve(import.meta.dirname, '../..');
const DIR = resolve(ROOT, 'docs/designs/components');
const SHEET = resolve(DIR, 'index.html');
const CANVAS = resolve(DIR, 'canvas/canvas.json');

const components = readdirSync(resolve(ROOT, 'skills')).filter((d) => skillKind(resolve(ROOT, 'skills', d)) === 'component');

describe('docs/designs/components/index.html is the generator output', () => {
  it('exists', () => {
    expect(existsSync(SHEET), 'run: node scripts/build-design.mjs').toBe(true);
  });

  it('equals render() from scripts/build-design.mjs byte for byte', async () => {
    const { render } = await import('../../scripts/build-design.mjs');
    expect(readFileSync(SHEET, 'utf8')).toBe(render());
  });

  it('loads nothing external, under the same rule scripts/check.sh applies to skills/', () => {
    const html = existsSync(SHEET) ? readFileSync(SHEET, 'utf8') : '';
    const hits = html.split('\n').filter((line) => /<link[^>]+href=|\ssrc(set)?=|@import|url\(/.test(line) && !/src="data:|url\(data:|url\(#/.test(line));
    expect(hits).toEqual([]);
  });

  it('renders every component root class', () => {
    const html = existsSync(SHEET) ? readFileSync(SHEET, 'utf8') : '';
    expect(components.length).toBe(6);
    for (const c of components) expect(html, `${c} missing`).toContain(`class="auk-${c.replace(/^ui-/, '')}`);
  });

  it('pins the canvas projection when it exists', async () => {
    if (!existsSync(CANVAS)) return;
    const { renderCanvas } = await import('../../scripts/build-design.mjs');
    const canvas = renderCanvas();
    expect(readFileSync(CANVAS, 'utf8')).toBe(canvas['canvas.json']);
    const listed = JSON.parse(readFileSync(CANVAS, 'utf8')).artboards.map((a: { file: string }) => a.file);
    expect(listed.length).toBeGreaterThan(0);
    for (const file of listed) {
      const path = resolve(DIR, 'canvas', file);
      expect(existsSync(path), `${file} listed in canvas.json is missing`).toBe(true);
      expect(readFileSync(path, 'utf8'), file).toBe(canvas[file]);
    }
  });
});

describe('validateRoles', () => {
  it('names a misspelled role', async () => {
    const { validateRoles } = await import('../../scripts/build-design.mjs');
    expect(() => validateRoles(':root { --auk-role-primary: #155e75; --auk-role-primry: #155e75; }')).toThrow(/--auk-role-primry/);
    expect(() => validateRoles(':root { --auk-role-primary: #155e75; }')).not.toThrow();
  });
});

describe('the generator never rewrites the sheet by accident', () => {
  it('a bare --roles flag exits non-zero and leaves the sheet untouched', () => {
    const before = readFileSync(SHEET, 'utf8');
    const run = spawnSync(process.execPath, [resolve(ROOT, 'scripts/build-design.mjs'), '--roles'], { encoding: 'utf8' });
    expect(run.status).toBe(1);
    expect(run.stderr).toMatch(/--roles/);
    expect(readFileSync(SHEET, 'utf8')).toBe(before);
  });

  it('fills a fifth alert region with sample text rather than "undefined"', async () => {
    const { fillAlerts } = await import('../../scripts/build-design.mjs');
    const html = '<span data-part="message"></span>'.repeat(5);
    const filled = fillAlerts(html);
    expect(filled).not.toContain('undefined');
    expect(filled.match(/<span data-part="message">[^<]+<\/span>/g)).toHaveLength(5);
  });
});
